titanic

In [224]:
import pandas as pd

In [197]:
t = pd.read_csv('titanic.csv')
t.head(6)

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0
5,6,"Moran, Mr. James",3,male,NaN,0,0,330877,8.4583,NaN,Q,0

In [198]:
x = t.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'], axis='columns')

In [199]:
x = x.drop(['Survived'], axis='columns')
y = t['Survived']

In [200]:
dummies = pd.get_dummies(x.Sex)

In [201]:
x = pd.concat([x, dummies], axis='columns')

In [202]:
x.drop(['Sex'], axis='columns', inplace=True)

In [203]:
x.Age = x.Age.fillna(x.Age.mean())

In [204]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [205]:
print(len(X_test))
print(len(X_train))

268
623

In [206]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [207]:
model.fit(X_train, y_train)

GaussianNB()

In [208]:
model.score(X_test, y_test)

0.7910447761194029

In [209]:
y_test[:10]

638    0
874    1
664    1
552    0
717    1
290    1
358    1
503    0
554    1
562    0
Name: Survived, dtype: int64

In [210]:
model.predict(X_test[:10])

array([1, 1, 0, 0, 1, 1, 1, 1, 1, 0])

In [211]:
model.predict_proba(X_test[:10])

array([[0.06748483, 0.93251517],
       [0.03437501, 0.96562499],
       [0.98820373, 0.01179627],
       [0.98969222, 0.01030778],
       [0.03504587, 0.96495413],
       [0.00210116, 0.99789884],
       [0.0787471 , 0.9212529 ],
       [0.08303998, 0.91696002],
       [0.07161505, 0.92838495],
       [0.97645656, 0.02354344]])

email spam

In [212]:
s = pd.read_csv('spam.csv')
s.head(5)

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [213]:
s.groupby('Category').describe()

         Message                                                            \
           count unique                                                top
Category
ham         4825   4516                             Sorry, I'll call later
spam         747    641  Please call our customer service representativ...


         freq
Category
ham        30
spam        4

In [214]:
s['spam'] = s['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [215]:
s.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [216]:
X_train, X_test, y_train, y_test = train_test_split(s.Message, s.spam, test_size=0.3)

In [217]:
#countvectorizer technic
#bernoulli naive bayes == when features are binary numbers
#multinomial naive bayes == when the data is discret(statistical), meaning it has a range and frequency (ex 1to5)
#gaussian naive bayes == when data has a normal distribution

In [218]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [219]:
v = CountVectorizer()
model = MultinomialNB()

#countvectorizer
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:3]

#multinomialnb
model.fit(X_train_count, y_train)

MultinomialNB()

In [220]:
X_test_count = v.transform(X_test)
model.score(X_test_count, y_test)

0.9856459330143541

In [221]:
#simplifying the code using the API
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [222]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [223]:
clf.score(X_test, y_test)

0.9856459330143541

WINE **DATASET**

In [231]:
from sklearn.datasets import load_wine
wine = load_wine()
dir(wine)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [254]:
w = pd.DataFrame(wine.data, columns=wine.feature_names)
w['Category'] = wine.target

In [241]:
w.groupby(['Category']).describe()

         alcohol                                                             \
           count       mean       std    min     25%     50%     75%    max
Category
0           59.0  13.744746  0.462125  12.85  13.400  13.750  14.100  14.83
1           71.0  12.278732  0.537964  11.03  11.915  12.290  12.515  13.86
2           48.0  13.153750  0.530241  12.20  12.805  13.165  13.505  14.34

         malic_acid            ... od280/od315_of_diluted_wines       proline  \
              count      mean  ...                          75%   max   count
Category                       ...
0              59.0  2.010678  ...                         3.42  4.00    59.0
1              71.0  1.932676  ...                         3.16  3.69    71.0
2              48.0  3.333750  ...                         1.82  2.47    48.0


                 mean         std    min    25%     50%     75%     max
Category
0         1115.711864  221.520767  680.0  987.5  1095.0  1280.0  1680.0
1          519.507042  157.211220  278.0  406.5   495.0   625.0   985.0
2          629.895833  115.097043  415.0  545.0   627.5   695.0   880.0

[3 rows x 104 columns]

In [246]:
x = w.drop(['Category'], axis='columns')
x.head(2)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0

In [247]:
y = w['Category']
y.head(2)

0    0
1    0
Name: Category, dtype: int64

In [277]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=100)

In [278]:
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [279]:
model.score(X_test, y_test)

1.0

In [280]:
mnc = MultinomialNB()
mnc.fit(X_train, y_train)

MultinomialNB()

In [281]:
model.score(X_test, y_test)

1.0